### ISSUE TITLE
Use .env instead of hardcoded varibles

### ISSUE THREAD

**Issue by Chemaclass** [jonpoischen/spam_messenger#1]
Instead of having hardcoded:

* `INSERT_FRIEND_HERE`
* `YOUR_EMAIL`
* `YOUR_PASSWORD`

We should have defined these variables in a (git) ignored `.env` file and get the values from there.

HINT: https://github.com/bkeepers/dotenv

**Comment by jonpoischen** [comment]
Those are meant to be replaced when git cloning but thanks for pointing this out
